//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChrisWebsite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVC_SKP_OevelserEntities : DbContext
    {
        public MVC_SKP_OevelserEntities()
            : base("name=MVC_SKP_OevelserEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN_LEV_Chair> ADMIN_LEV_Chair { get; set; }
        public virtual DbSet<LOW_LEV_Chair> LOW_LEV_Chair { get; set; }
    }
}
